# From https://github.com/giantswarm/apiextensions/blob/741707fa9cb6f236f4203805263cc64111b6f924/pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go#L16-L57
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awscontrolplanes.infrastructure.giantswarm.io
spec:
  group: infrastructure.giantswarm.io
  names:
    kind: AWSControlPlane
    plural: awscontrolplanes
    singular: awscontrolplane
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: false
    storage: false
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
            properties:
              instanceType:
                type: string
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: |
          This is a placeholder description of the AWSControlPlane CRD. It should briefly
          explain the purpose of the CRD, mention the operator owning it, may also state
          the provider where it is in use and say with which release it has been introduced
          or phased out.
        properties:
          spec:
            type: object
            properties:
              availabilityZones:
                type: array
                items:
                  type: string
              instanceType:
                type: string
  conversion:
    strategy: None
