# From https://github.com/giantswarm/apiextensions/blob/741707fa9cb6f236f4203805263cc64111b6f924/pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go#L16-L57
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awscontrolplanes.infrastructure.giantswarm.io
spec:
  group: infrastructure.giantswarm.io
  names:
    kind: AWSControlPlane
    plural: awscontrolplanes
    singular: awscontrolplane
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: false
    storage: false
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              instanceType:
                type: string
            type: object
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              availabilityZones:
                items:
                  type: string
                type: array
              instanceType:
                type: string
            type: object
  conversion:
    strategy: None
