# From https://github.com/giantswarm/apiextensions/blob/e11354aee7703fa74c504978a3d4b525c7814730/pkg/apis/infrastructure/v1alpha2/aws_cluster_types.go#L14-L56
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsclusters.infrastructure.giantswarm.io
spec:
  group: infrastructure.giantswarm.io
  names:
    kind: AWSCluster
    plural: awsclusters
    singular: awscluster
  version: v1alpha2
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cluster:
              properties:
                description:
                  maxLength: 100
                  type: string
                dns:
                  properties:
                    domain:
                      type: string
                    provider:
                      properties:
                        master:
                          properties:
                            availabilityZone:
                              type: string
                            instanceType:
                              type: string
                          type: object
                        region:
                          type: string
                      type: object
                  type: object
              type: object
          type: object
        status:
          type: object
          description: >
            **Note:** The `.status` section schema has been added for demonstration
            purposes only.
          properties:
            cluster:
              type: object
              properties:
                conditions:
                  type: array
                  description: >
                    Holds information to explain the current condition(s) of the cluster.
                  items:
                    type: object
                    description: An individual condition.
                    required: ["lastTransitionTime", "type"]
                    properties:
                      lastTransitionTime:
                        type: string
                        description: |
                          Time the cluster assumed the given condition.
                      type:
                        type: string
                        description: |
                          Condition string. Possible values:

                          - `Creating` - Cluster is being created.
                          - `Created` - Cluster creation has been finished.
                          - `Updating` - Cluster is undergoing an update, e. g. for a release upgrade.
                          - `Updated` - Cluster update is finished.
                        enum:
                          - Creating
                          - Created
                          - Updating
                          - Updated
