# From https://github.com/giantswarm/apiextensions/blob/71155aa0f5b7e5e88f31764039e27752c6aee580/pkg/apis/infrastructure/v1alpha2/aws_machine_deployment_types.go#L14-L68
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsmachinedeployments.infrastructure.giantswarm.io
spec:
  group: infrastructure.giantswarm.io
  names:
    kind: AWSMachineDeployment
    plural: awsmachinedeployments
    singular: awsmachinedeployment
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            nodePool:
              properties:
                description:
                  maxLength: 100
                  type: string
                machine:
                  properties:
                    dockerVolumeSizeGB:
                      format: int32
                      type: integer
                    kubeletVolumeSizeGB:
                      format: int32
                      type: integer
                  type: object
                scaling:
                  properties:
                    max:
                      format: int32
                      type: integer
                    min:
                      format: int32
                      type: integer
                  type: object
              type: object
            provider:
              properties:
                availabilityZones:
                  items:
                    type: string
                  type: array
                worker:
                  properties:
                    instanceType:
                      type: string
              type: object
          type: object
  version: v1alpha2
