# From https://github.com/giantswarm/apiextensions/blob/95ba5a91cb4431ab8e6dee2eb9e372616573b1b4/pkg/apis/application/v1alpha1/chart_types.go#L14-L66
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: charts.application.giantswarm.io
spec:
  group: application.giantswarm.io
  scope: Namespaced
  version: v1alpha1
  names:
    kind: Chart
    plural: charts
    singular: chart
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
            namespace:
              type: string
            config:
              type: object
              properties:
                configMap:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    resourceVersion:
                      type: string
                  required: ["name", "namespace"]
                secret:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    resourceVersion:
                      type: string
                  required: ["name", "namespace"]
            tarballURL:
              type: string
              format: uri
            version:
              type: string
          required: ["name", "namespace", "tarballURL", "version"]
