# From https://github.com/giantswarm/apiextensions/blob/acdbf019d0f8cf6d839bda21fa93440fe9faad16/pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go#L15-L63
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: g8scontrolplanes.infrastructure.giantswarm.io
spec:
  group: infrastructure.giantswarm.io
  scope: Namespaced
  names:
    kind: G8sControlPlane
    plural: g8scontrolplanes
    singular: g8scontrolplane
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: false
    storage: false
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              replicas:
                type: int
            type: object
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              replicas:
                type: int
              infrastructureRef:
                properties:
                  kind:
                    type: string
                  namespace:
                    type: string
                  name:
                    type: string
                  apiVersion:
                    type: string
                type: object
            type: object
  conversion:
    strategy: None