# From https://github.com/giantswarm/apiextensions/blob/490ba82fe60e6549217aa735f1fe3e4b589d4dfc/pkg/apis/release/v1alpha1/release_types.go#L21-L107
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: releases.release.giantswarm.io
spec:
  group: release.giantswarm.io
  scope: Cluster
  version: v1alpha1
  names:
    kind: Release
    plural: releases
    singular: release
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            changelog:
              type: array
              minItems: 1
              items:
                type: object
                properties:
                  component:
                    type: string
                    minLength: 3
                  description:
                    type: string
                    minLength: 3
                  kind:
                    enum:
                    - added
                    - changed
                    - deprecated
                    - fixed
                    - removed
                    - security
                required:
                - component
                - description
                - kind
            components:
              type: array
              minItems: 1
              items:
                type: object
                properties:
                  name:
                    type: string
                    minLength: 3
                  version:
                    type: string
                    minLength: 5
            parentVersion:
              type: string
              pattern: "^\\d+\\.\\d+\\.\\d+$"
            version:
              type: string
              minLength: 5
          required:
          - changelog
          - components
          - parentVersion
          - version
        status:
          type: object
          properties:
            cycle:
              type: object
              properties:
                disabledDate:
                  type: string
                  format: date
                enabledDate:
                  type: string
                  format: date
                phase:
                  enum:
                  - upcoming
                  - enabled
                  - disabled
                  - eol
              required:
              - phase
