# From https://github.com/giantswarm/apiextensions/blob/490ba82fe60e6549217aa735f1fe3e4b589d4dfc/pkg/apis/release/v1alpha1/release_cycle_types.go#L19-L54
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: releasecycles.release.giantswarm.io
spec:
  group: release.giantswarm.io
  scope: Cluster
  version: v1alpha1
  names:
    kind: ReleaseCycle
    plural: releasecycles
    singular: releasecycle
  subresources:
    status: {}
  validation:
    # Note: When changing ReleaseCycle CRD schema please make sure to update
    # ReleaseCycle details in Release CRD schema accordingly.
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            disabledDate:
              type: string
              format: date
            enabledDate:
              type: string
              format: date
            phase:
              enum:
              - upcoming
              - enabled
              - disabled
              - eol
          required:
          - phase
