version: 2.1
orbs:
  architect: giantswarm/architect@9.4.0

workflows:
  build-workflow:
    jobs:
    - architect/go-build:
        context: architect
        name: go-build
        binary: crd-docs-generator
        architectures: "linux/amd64,linux/arm64,darwin/amd64,darwin/arm64,windows/amd64,windows/arm64"
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
        platforms: "linux/amd64"

    - architect/upload-release-assets:
        binary: crd-docs-generator
        context: architect
        name: upload-release-assets
        requires:
        - go-build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
